--- #looping samples for ansible
- hosts: webservers
  become: true

  tasks:
    - name: install softwares with yum
      yum:
        name: "{{ item }}"
        state: latest
      loop: 
        - git
        - python3-pip
        - httpd


