--- #looping samples for ansible
- hosts: webservers
  become: true

  tasks:
    - name: install softwares with yum
      yum:
        name: "{{ item }}"
        state: latest
      loop: 
        - git
        - python3-pip
        - httpd


- hosts: dbservers
  become: true
  vars:
    softwares:
      - git
      - python3-pip
      - httpd

  tasks:
    - name: install softwares from variable
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ softwares }}"