---
- hosts: linux
  become: true

  tasks:
    - name: install appache software
      yum:
        name: "{{software-list}}"
        state: latest

    - name: install nmap-ncat software
      yum:
        name: nmap-ncat
        state: latest
