--- #template example
- hosts: linux
  gather_facts: false
  become: true
  vars:
    code_name: whisky
    version: 4.5

  tasks:
    - name: deploy config file
      template:
        src: ./templates/config.j2
        dest: /opt/config
